// <auto-generated />
using System;
using DIM_Vision_Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DIM_Vision_Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20181221174448_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DIM_Vision_Entities.Entities.Choice", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("CboiceType");

                    b.Property<Guid>("GrammarId");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("GrammarId");

                    b.ToTable("Choices");
                });

            modelBuilder.Entity("DIM_Vision_Entities.Entities.EmbeddedChoice", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<Guid>("ChoiceId");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.ToTable("EmbeddedChoice");
                });

            modelBuilder.Entity("DIM_Vision_Entities.Entities.Grammar", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<int>("GrammarType");

                    b.Property<string>("Name");

                    b.Property<int>("Order");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("Grammars");
                });

            modelBuilder.Entity("DIM_Vision_Entities.Entities.Choice", b =>
                {
                    b.HasOne("DIM_Vision_Entities.Entities.Grammar", "Grammar")
                        .WithMany("Choices")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DIM_Vision_Entities.Entities.EmbeddedChoice", b =>
                {
                    b.HasOne("DIM_Vision_Entities.Entities.Choice", "Choice")
                        .WithMany("EmbeddedChoices")
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
